* 공공데이터 포털 도로교통공단_월별_주야별 교통사고 통계: https://www.data.go.kr/data/15070318/fileData.do 
* 소상공인시장진흥공단_상가(상권)정보 : https://www.data.go.kr/data/15083033/fileData.do
* glob : 유닉스 스타일의 경로명 패턴 확장

# 1. 절대 경로
* 절대 경로는 어떠한 웹페이지나 파일이 가진 고유한 경로로 최상위 디렉토리가 포함된 경로
* 예) C:\user\documents

# 2. 상대 경로
* 상대 경로는 현재 위치한 곳을 기준으로 하는 경로
* /는 루트
* ./는 현재 위치
* ../는 현재 위치의 상위 폴터
* ../../는 두 단계 위의 상위 폴더

In [1]:
# 실습 파일 경로 확인
%pwd

'C:\\연구실\\공부\\데이터 분석'

In [2]:
import os
os.getcwd()

'C:\\연구실\\공부\\데이터 분석'

In [11]:
from glob import glob

# data 폴더 안에 있는 파일 불러오기
file_name = glob("data/*")[0]
file_name

'data\\도로교통공단_월별 주야별 교통사고 통계_20221231.csv'

In [12]:
import pandas as pd

In [14]:
# csv 파일 읽어오기
pd.read_csv(file_name, encoding="cp949") # 유니코드 에러 방지

    발생월 주야   사고건수  사망자수  중상자수   경상자수  부상신고자수
0     1  주   9588    90  2546  10464     792
1     1  야   6306   103  1690   6795     504
2     2  주   7575    78  2001   8228     657
3     2  야   4787    83  1300   4981     421
4     3  주   8322    96  2167   8783     600
5     3  야   5298    87  1473   5393     437
6     4  주  10472   112  2798  11475     961
7     4  야   6000   104  1680   6398     487
8     5  주  11749   136  3198  12531    1107
9     5  야   6316    99  1674   6676     586
10    6  주  10377   139  2746  11055     940
11    6  야   6104    92  1692   6396     600
12    7  주  10780   120  2802  11993    1032
13    7  야   6335   121  1697   6684     604
14    8  주  10360   124  2669  11560     953
15    8  야   6136   118  1632   6598     542
16    9  주  10799   146  2754  11810     967
17    9  야   6417   111  1694   6805     614
18   10  주  11590   168  3083  12795    1097
19   10  야   6918   117  1800   7384     616
20   11  주  10944   159  2838  11474    1017
21   11  야   6634    98  1706   7087     621
22   12  주  10416   133  2510  11547     920
23   12  야   6613   101  1565   7518     583

## 여러 파일을 한번에 로드하는 방법

In [17]:
# data/store 폴더의 csv 파일에 대한 경로 확인
file_csv = glob("data/store/*.csv")
file_csv

['data/store\\소상공인시장진흥공단_상가(상권)정보_강원_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경기_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_광주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대구_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대전_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_부산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_세종_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_울산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_인천_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_제주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충북_202306.csv']

In [25]:
pd.read_csv(file_csv[0], low_memory=False)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0084547,금강산노래광장,NaN,I2,음식,I211,주점,I21101,일반 유흥 주점,I56211,...,4217010300007470000000086,파크장,강원특별자치도 동해시 송정로 11,240806,25789,NaN,지,NaN,129.127525,37.495265
1,MA010120220805430826,에이치속눈썹수강아카데미,NaN,S2,수리·개인,S207,이용·미용,S20702,피부 관리실,S96113,...,4211039021110620001000001,NaN,강원특별자치도 춘천시 동내면 외솔길19번길 80-36,200883,24401,NaN,NaN,NaN,127.758764,37.857831
2,MA010120220805430903,엔젤,NaN,I2,음식,I201,한식,I20101,백반/한정식,I55109,...,4277032022103660000008290,NaN,강원특별자치도 정선군 남면 민둥산로 175-13,233837,26148,NaN,NaN,NaN,128.792089,37.259788
3,MA010120220805430941,누베헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,4211012500100440010000008,춘천파크자이,강원특별자치도 춘천시 스포츠타운길 458,200200,24472,NaN,3,NaN,127.707653,37.867744
4,MA010120220805430946,공차,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4213033023113500001000001,NaN,강원특별자치도 원주시 지정면 신지정로 211,220821,26354,NaN,NaN,NaN,127.872713,37.374189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94907,MA0101202303A0026148,참식품,NaN,G2,소매,G205,식료품 소매,G20505,수산물 소매업,G47214,...,4221010400104730033016699,NaN,강원특별자치도 속초시 중앙로129번길 43,217807,24832,NaN,1,NaN,128.589250,38.204533
94908,MA0101202303A0014245,옥도건어물삼척점,NaN,G2,소매,G205,식료품 소매,G20504,건어물/젓갈 소매업,G47213,...,4223012000103340008000001,NaN,강원특별자치도 삼척시 오십천로 453,245938,25929,NaN,1,NaN,129.168006,37.439799
94909,MA0101202303A0003084,달래해장강릉,교동점,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4215011000118290003026615,NaN,강원특별자치도 강릉시 솔올로 64,210924,25510,NaN,1,NaN,128.878913,37.767571
94910,MA0101202303A0029915,나드리반찬,NaN,G2,소매,G205,식료품 소매,G20509,반찬/식료품 소매업,G47218,...,4275025021109450006018064,농협,강원특별자치도 영월군 영월읍 중앙로 40,230805,26236,NaN,NaN,NaN,128.467888,37.183080
94911,MA0101202303A0038234,수학공부,NaN,P1,교육,P105,일반 교육,P10501,입시·교과학원,P85501,...,4211012400107100000014925,NaN,강원특별자치도 춘천시 효석로77번길 5-19,200936,24382,NaN,NaN,NaN,127.738035,37.861067

In [21]:
file_list = []
# 반복문을 이용해 파일 한꺼번에 불러오기
for file_csv_name in file_csv:
    print(file_csv_name)
    temp = pd.read_csv(file_csv_name, low_memory=False)
    file_list.append(temp)

data/store\소상공인시장진흥공단_상가(상권)정보_강원_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_경기_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_경남_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_경북_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_광주_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_대구_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_대전_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_부산_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_세종_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_울산_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_인천_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_전남_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_전북_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_제주_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_충남_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_충북_202306.csv

In [26]:
file_list[0]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0084547,금강산노래광장,NaN,I2,음식,I211,주점,I21101,일반 유흥 주점,I56211,...,4217010300007470000000086,파크장,강원특별자치도 동해시 송정로 11,240806,25789,NaN,지,NaN,129.127525,37.495265
1,MA010120220805430826,에이치속눈썹수강아카데미,NaN,S2,수리·개인,S207,이용·미용,S20702,피부 관리실,S96113,...,4211039021110620001000001,NaN,강원특별자치도 춘천시 동내면 외솔길19번길 80-36,200883,24401,NaN,NaN,NaN,127.758764,37.857831
2,MA010120220805430903,엔젤,NaN,I2,음식,I201,한식,I20101,백반/한정식,I55109,...,4277032022103660000008290,NaN,강원특별자치도 정선군 남면 민둥산로 175-13,233837,26148,NaN,NaN,NaN,128.792089,37.259788
3,MA010120220805430941,누베헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,4211012500100440010000008,춘천파크자이,강원특별자치도 춘천시 스포츠타운길 458,200200,24472,NaN,3,NaN,127.707653,37.867744
4,MA010120220805430946,공차,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4213033023113500001000001,NaN,강원특별자치도 원주시 지정면 신지정로 211,220821,26354,NaN,NaN,NaN,127.872713,37.374189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94907,MA0101202303A0026148,참식품,NaN,G2,소매,G205,식료품 소매,G20505,수산물 소매업,G47214,...,4221010400104730033016699,NaN,강원특별자치도 속초시 중앙로129번길 43,217807,24832,NaN,1,NaN,128.589250,38.204533
94908,MA0101202303A0014245,옥도건어물삼척점,NaN,G2,소매,G205,식료품 소매,G20504,건어물/젓갈 소매업,G47213,...,4223012000103340008000001,NaN,강원특별자치도 삼척시 오십천로 453,245938,25929,NaN,1,NaN,129.168006,37.439799
94909,MA0101202303A0003084,달래해장강릉,교동점,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4215011000118290003026615,NaN,강원특별자치도 강릉시 솔올로 64,210924,25510,NaN,1,NaN,128.878913,37.767571
94910,MA0101202303A0029915,나드리반찬,NaN,G2,소매,G205,식료품 소매,G20509,반찬/식료품 소매업,G47218,...,4275025021109450006018064,농협,강원특별자치도 영월군 영월읍 중앙로 40,230805,26236,NaN,NaN,NaN,128.467888,37.183080
94911,MA0101202303A0038234,수학공부,NaN,P1,교육,P105,일반 교육,P10501,입시·교과학원,P85501,...,4211012400107100000014925,NaN,강원특별자치도 춘천시 효석로77번길 5-19,200936,24382,NaN,NaN,NaN,127.738035,37.861067

In [28]:
len(file_list) # 17개의 파일

17

In [27]:
df = pd.concat(file_list) # 콜롬 명이 같으면, 하나의 데이터프레임으로 합치기
df.shape

(2417759, 39)

In [29]:
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0084547,금강산노래광장,NaN,I2,음식,I211,주점,I21101,일반 유흥 주점,I56211,...,4217010300007470000000086,파크장,강원특별자치도 동해시 송정로 11,240806,25789,NaN,지,NaN,129.127525,37.495265
1,MA010120220805430826,에이치속눈썹수강아카데미,NaN,S2,수리·개인,S207,이용·미용,S20702,피부 관리실,S96113,...,4211039021110620001000001,NaN,강원특별자치도 춘천시 동내면 외솔길19번길 80-36,200883,24401,NaN,NaN,NaN,127.758764,37.857831
2,MA010120220805430903,엔젤,NaN,I2,음식,I201,한식,I20101,백반/한정식,I55109,...,4277032022103660000008290,NaN,강원특별자치도 정선군 남면 민둥산로 175-13,233837,26148,NaN,NaN,NaN,128.792089,37.259788
3,MA010120220805430941,누베헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,4211012500100440010000008,춘천파크자이,강원특별자치도 춘천시 스포츠타운길 458,200200,24472,NaN,3,NaN,127.707653,37.867744
4,MA010120220805430946,공차,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4213033023113500001000001,NaN,강원특별자치도 원주시 지정면 신지정로 211,220821,26354,NaN,NaN,NaN,127.872713,37.374189

In [30]:
# 데이터프레임 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2417759 entries, 0 to 81722
Data columns (total 39 columns):
 #   Column     Dtype
---  ------     -----
 0   상가업소번호     object
 1   상호명        object
 2   지점명        object
 3   상권업종대분류코드  object
 4   상권업종대분류명   object
 5   상권업종중분류코드  object
 6   상권업종중분류명   object
 7   상권업종소분류코드  object
 8   상권업종소분류명   object
 9   표준산업분류코드   object
 10  표준산업분류명    object
 11  시도코드       int64
 12  시도명        object
 13  시군구코드      int64
 14  시군구명       object
 15  행정동코드      int64
 16  행정동명       object
 17  법정동코드      int64
 18  법정동명       object
 19  지번코드       int64
 20  대지구분코드     int64
 21  대지구분명      object
 22  지번본번지      float64
 23  지번부번지      float64
 24  지번주소       object
 25  도로명코드      int64
 26  도로명        object
 27  건물본번지      float64
 28  건물부번지      float64
 29  건물관리번호     object
 30  건물명        object
 31  도로명주소      object
 32  구우편번호      int64
 33  신우편번호      int64
 34  동정보        float64
 35  층정보        object
 36  호정보        float64
 37  경도         float64
 38  위도         float64
dtypes: float64(8), int64(9), object(22)
memory usage: 737.8+ MB